(()=>{const C=document.getElementById('view'),ctx=C.getContext('2d'),$=s=>document.querySelector(s),partsEl=$('#parts'),controls=$('#controls');const colors=['#8d9b72','#71805d','#9a896b','#657654','#788764','#59694e','#a09372','#6e7d5b','#82916b','#536247','#968568','#627052'];let parts=[],sel=0,tab='size',step=.5,yaw=-.62,pitch=-.34,zoom=42,drag=null,moved=false,pointers=new Map(),pinch=0,work='model',anim='walk',playing=false,animT=0,lastFrame=0,animSpeed=1,animAmp=1,poseParts=null,realMesh=null,showReal=true;

const REAL_CAT_URL='https://raw.githubusercontent.com/mineclonia-mirror/mineclonia/main/mods/ENTITIES/mobs_mc/models/mobs_mc_cat.b3d';
function cstr(v,s,end){let o='';while(s.p<end){let c=v.getUint8(s.p++);if(!c)break;o+=String.fromCharCode(c)}return o}
function mat4(pos,scale,q){const w=q[0],x=q[1],y=q[2],z=q[3],xx=x*x,yy=y*y,zz=z*z,xy=x*y,xz=x*z,yz=y*z,wx=w*x,wy=w*y,wz=w*z;return[(1-2*(yy+zz))*scale[0],(2*(xy+wz))*scale[0],(2*(xz-wy))*scale[0],0,(2*(xy-wz))*scale[1],(1-2*(xx+zz))*scale[1],(2*(yz+wx))*scale[1],0,(2*(xz+wy))*scale[2],(2*(yz-wx))*scale[2],(1-2*(xx+yy))*scale[2],0,pos[0],pos[1],pos[2],1]}
function mul4(a,b){const o=new Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
function tr3(m,x,y,z){return{x:m[0]*x+m[4]*y+m[8]*z+m[12],y:m[1]*x+m[5]*y+m[9]*z+m[13],z:m[2]*x+m[6]*y+m[10]*z+m[14]}}
function parseB3D(buf){const v=new DataView(buf),td=new TextDecoder('latin1'),out={p:[],idx:[],nodes:[]};let pos=0;const tag=()=>{let a=new Uint8Array(buf,pos,4);pos+=4;return td.decode(a)},i32=()=>{let n=v.getInt32(pos,true);pos+=4;return n},f32=()=>{let n=v.getFloat32(pos,true);pos+=4;return n};function chunks(end,m,name='root'){while(pos+8<=end){let t=tag(),size=i32(),ce=Math.min(end,pos+Math.max(0,size));if(t==='NODE'){let st={p:pos},nm=cstr(v,st,ce);pos=st.p;if(pos+40<=ce){let p=[f32(),f32(),f32()],sc=[f32(),f32(),f32()],q=[f32(),f32(),f32(),f32()],mm=mul4(m,mat4(p,sc,q));out.nodes.push({name:nm,pos:p,scale:sc});chunks(ce,mm,nm)}else pos=ce}else if(t==='MESH'){if(pos+4>ce){pos=ce;continue}i32();let verts=null;while(pos+8<=ce){let mt=tag(),ms=i32(),me=Math.min(ce,pos+Math.max(0,ms));if(mt==='VRTS'&&pos+12<=me){let flags=i32(),sets=i32(),sz=i32(),pp=[];while(pos<me){let stride=12+((flags&1)?12:0)+((flags&2)?16:0)+Math.max(0,sets*sz)*4;if(pos+stride>me)break;let z=tr3(m,f32(),f32(),f32());pp.push(z.x,z.y,z.z);if(flags&1){f32();f32();f32()}if(flags&2){f32();f32();f32();f32()}for(let n=0;n<sets*sz;n++)f32()}verts=pp;pos=me}else if(mt==='TRIS'&&verts){if(pos+4>me){pos=me;continue}i32();let base=out.p.length/3;out.p.push(...verts);while(pos+12<=me)out.idx.push(base+i32(),base+i32(),base+i32());pos=me}else pos=me}pos=ce}else pos=ce}pos=end}if(tag()!=='BB3D')throw Error('B3D');let root=Math.min(v.byteLength,pos+i32());if(pos+4<=root)i32();chunks(root,[1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1]);let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<out.p.length;i+=3)for(let k=0;k<3;k++){min[k]=Math.min(min[k],out.p[i+k]);max[k]=Math.max(max[k],out.p[i+k])}let c=min.map((x,k)=>(x+max[k])/2),span=Math.max(...max.map((x,k)=>x-min[k]))||1,s=14/span;for(let i=0;i<out.p.length;i+=3){out.p[i]=(out.p[i]-c[0])*s;out.p[i+1]=(out.p[i+1]-c[1])*s;out.p[i+2]=(out.p[i+2]-c[2])*s}return out}
async function loadRealCat(){let el=$('#realStatus');try{let r=await fetch(REAL_CAT_URL,{cache:'force-cache'});if(!r.ok)throw Error(r.status);realMesh=parseB3D(await r.arrayBuffer());el.textContent='Gerçek kedi · '+Math.round(realMesh.p.length/3)+' vertex';el.classList.remove('err');draw()}catch(e){console.error(e);el.textContent='Gerçek kedi yüklenemedi';el.classList.add('err')}}
function drawRealMesh(){if(!realMesh||!showReal)return;let p=realMesh.p,idx=realMesh.idx,fs=[];for(let i=0;i<idx.length;i+=3){let vv=[];for(let k=0;k<3;k++){let n=idx[i+k]*3;vv.push(project({x:p[n],y:p[n+1],z:p[n+2]}))}fs.push({v:vv,z:(vv[0][2]+vv[1][2]+vv[2][2])/3})}fs.sort((a,b)=>b.z-a.z);ctx.save();ctx.globalAlpha=.28;ctx.fillStyle='#b8d47d';ctx.strokeStyle='#dff3b0';ctx.lineWidth=.45;for(let f of fs){ctx.beginPath();ctx.moveTo(f.v[0][0],f.v[0][1]);ctx.lineTo(f.v[1][0],f.v[1][1]);ctx.lineTo(f.v[2][0],f.v[2][1]);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()}

function P(name,x,y,z,sx,sy,sz,rx=0,ry=0,rz=0){return{id:crypto.randomUUID?.()||Math.random().toString(36).slice(2),name,x,y,z,sx,sy,sz,rx,ry,rz,color:colors[parts.length%colors.length]}}
function cat(){parts=[];parts.push(P('Gövde',0,0,0,4,2.25,7),P('Kafa',0,.35,-4.05,3,2.5,2.7),P('Burun',0,-.05,-5.55,2,1.25,1.4),P('Ön sol bacak',-1.35,-1.9,-2.35,1,3,1),P('Ön sağ bacak',1.35,-1.9,-2.35,1,3,1),P('Arka sol bacak',-1.35,-1.9,2.35,1,3,1),P('Arka sağ bacak',1.35,-1.9,2.35,1,3,1),P('Kuyruk 1',0,.15,4.55,1.1,1.1,3.2,-18),P('Kuyruk 2',0,.85,7.15,.9,.9,3,-10));sel=0;sync()}
function komodo(){parts=[];parts.push(P('Gövde',0,0,0,5,2.25,9),P('Boyun',0,.05,-5.25,3.1,1.8,2.8),P('Kafa',0,.05,-7.15,3.5,1.9,3),P('Burun',0,-.12,-9.05,3,1.35,1.7),P('Ön sol bacak',-2.35,-1.45,-3.1,1.2,2.1,1.4,0,0,-12),P('Ön sağ bacak',2.35,-1.45,-3.1,1.2,2.1,1.4,0,0,12),P('Arka sol bacak',-2.45,-1.45,3.2,1.35,2.1,1.6,0,0,-15),P('Arka sağ bacak',2.45,-1.45,3.2,1.35,2.1,1.6,0,0,15),P('Kuyruk 1',0,.05,5.9,2.4,1.65,4),P('Kuyruk 2',0,.05,9.25,1.75,1.25,3.5),P('Kuyruk 3',0,.05,12.15,1.1,.9,2.8),P('Kuyruk ucu',0,.05,14.45,.6,.55,2));sel=0;sync()}
function camera(v){let x=v.x,y=v.y,z=v.z,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),X=x*cy-z*sy,Z=x*sy+z*cy,Y=y*cp-Z*sp;Z=y*sp+Z*cp;return[X,Y,Z]}
function project(v){let q=camera(v);return[C.width/2+q[0]*zoom,C.height/2-q[1]*zoom,q[2]]}
function displayPart(p){if(work!=='animate')return p;let q={...p},t=animT*Math.PI*2,a=animAmp,n=(p.name||'').toLowerCase(),left=n.includes('sol'),front=n.includes('ön'),rear=n.includes('arka'),tail=n.includes('kuyruk'),head=n.includes('kafa')||n.includes('burun')||n.includes('boyun');if(anim==='walk'){if(n.includes('bacak')){let phase=((front&&left)||(rear&&!left))?0:Math.PI;q.rx+=(Math.sin(t+phase)*28*a)}if(tail)q.ry+=Math.sin(t+(parseInt(n.match(/\d+/)?.[0]||1)*.35))*12*a;if(head)q.ry+=Math.sin(t)*2*a;q.y+=Math.sin(t*2)*.08*a}else if(anim==='idle'){q.y+=Math.sin(t)*.08*a;if(head)q.rx+=Math.sin(t)*2*a;if(tail)q.ry+=Math.sin(t*.65)*5*a}else if(anim==='attack'){let k=Math.max(0,Math.sin(t));if(head){q.z-=k*.75*a;q.rx-=k*10*a}if(tail)q.ry+=Math.sin(t+1)*16*a}else if(anim==='tail'){if(tail)q.ry+=Math.sin(t+(parseInt(n.match(/\d+/)?.[0]||1)*.5))*28*a}return q}
function verts(p){p=displayPart(p);let a=[];for(let x of[-1,1])for(let y of[-1,1])for(let z of[-1,1]){let X=x*p.sx/2,Y=y*p.sy/2,Z=z*p.sz/2,ax=p.rx*Math.PI/180,ay=p.ry*Math.PI/180,az=p.rz*Math.PI/180,y1=Y*Math.cos(ax)-Z*Math.sin(ax),z1=Y*Math.sin(ax)+Z*Math.cos(ax);Y=y1;Z=z1;let x1=X*Math.cos(ay)+Z*Math.sin(ay);z1=-X*Math.sin(ay)+Z*Math.cos(ay);X=x1;Z=z1;x1=X*Math.cos(az)-Y*Math.sin(az);y1=X*Math.sin(az)+Y*Math.cos(az);a.push(project({x:x1+p.x,y:y1+p.y,z:Z+p.z}))}return a}
const faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]];
function draw(){let r=C.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.round(r.width*d),h=Math.round(r.height*d);if(C.width!==w||C.height!==h){C.width=w;C.height=h}ctx.clearRect(0,0,C.width,C.height);ctx.strokeStyle='#ffffff0c';ctx.lineWidth=1;for(let i=-16;i<=16;i++){let a=project({x:i,y:-3,z:-16}),b=project({x:i,y:-3,z:16});ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();a=project({x:-16,y:-3,z:i});b=project({x:16,y:-3,z:i});ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()}drawRealMesh();let fs=[];parts.forEach((p,pi)=>{let v=verts(p);faces.forEach(f=>fs.push({pi,f,v,z:f.reduce((s,i)=>s+v[i][2],0)/4}))});fs.sort((a,b)=>b.z-a.z);fs.forEach(q=>{ctx.beginPath();q.f.forEach((i,k)=>k?ctx.lineTo(q.v[i][0],q.v[i][1]):ctx.moveTo(q.v[i][0],q.v[i][1]));ctx.closePath();ctx.globalAlpha=q.pi===sel?.92:.72;ctx.fillStyle=parts[q.pi].color;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=q.pi===sel?'#fff':'#0b0d0f';ctx.lineWidth=q.pi===sel?2.4:1;ctx.stroke()})}
function pick(x,y){let best=-1,bd=Infinity;parts.forEach((p,i)=>{let q=project(p),d=(q[0]-x)**2+(q[1]-y)**2;if(d<bd){bd=d;best=i}});if(bd<140*140){sel=best;sync()}}
function fmt(n){return Math.round(n*100)/100}function renderControls(){let p=parts[sel];if(!p)return;let cfg=tab==='size'?[['X','sx'],['Y','sy'],['Z','sz']]:tab==='pos'?[['X','x'],['Y','y'],['Z','z']]:[['X°','rx'],['Y°','ry'],['Z°','rz']];controls.innerHTML=cfg.map(([l,k])=>'<div class="control"><span>'+l+'</span><button data-k="'+k+'" data-d="-1">−</button><output>'+fmt(p[k])+'</output><button data-k="'+k+'" data-d="1">+</button></div>').join('')}
function sync(){let p=parts[sel];if(!p){sel=Math.max(0,parts.length-1);p=parts[sel]}if(!p)return;$('#selName').textContent=p.name;$('#name').value=p.name;$('#count').textContent=parts.length+' kutu';$('#fpsBadge').textContent='Komodo · '+parts.length+' parça';partsEl.innerHTML=parts.map((x,i)=>'<button class="part '+(i===sel?'active':'')+'" data-i="'+i+'"><i style="background:'+x.color+'"></i>'+x.name+'</button>').join('');renderControls();draw()}
controls.onclick=e=>{let b=e.target.closest('button[data-k]');if(!b)return;let p=parts[sel],k=b.dataset.k,d=+b.dataset.d,inc=tab==='rot'?5:step;p[k]+=d*inc;if(tab==='size')p[k]=Math.max(.25,p[k]);sync()};partsEl.onclick=e=>{let b=e.target.closest('[data-i]');if(b){sel=+b.dataset.i;sync()}};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));tab=b.dataset.tab;renderControls()});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-step]').forEach(x=>x.classList.toggle('active',x===b));step=+b.dataset.step});
$('#name').onchange=e=>{parts[sel].name=e.target.value||parts[sel].name;sync()};$('#add').onclick=()=>{let q=parts[sel]||{x:0,y:0,z:0};parts.push(P('Yeni kutu',q.x,q.y,q.z,1,1,1));sel=parts.length-1;sync()};$('#dup').onclick=()=>{let q=parts[sel];if(!q)return;parts.push({...q,id:crypto.randomUUID?.()||Math.random().toString(36).slice(2),name:q.name+' kopya',x:q.x+.5});sel=parts.length-1;sync()};$('#del').onclick=()=>{if(parts.length<=1)return;parts.splice(sel,1);sel=Math.min(sel,parts.length-1);sync()};$('#reset').onclick=cat;$('#komodo').onclick=komodo;
$('#save').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'mineclonia-cuboid-project-v1',parts},null,2)],{type:'application/json'}));a.download='komodo-model.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#load').onchange=async e=>{try{let j=JSON.parse(await e.target.files[0].text());if(!Array.isArray(j.parts))throw 0;parts=j.parts;sel=0;sync()}catch{alert('Geçerli bir Voxel Model Studio projesi değil.')}e.target.value=''};
document.querySelectorAll('[data-work]').forEach(b=>b.onclick=()=>{work=b.dataset.work;document.querySelectorAll('[data-work]').forEach(x=>x.classList.toggle('active',x===b));$('#modelPanel').hidden=work!=='model';$('#animPanel').hidden=work!=='animate';$('#modeBadge').textContent=work==='animate'?'ANIMATE':'MODEL';document.body.classList.toggle('animating',work==='animate');if(work==='animate')draw()});
const animNames={idle:'Nefes',walk:'Yürüme',attack:'Saldırı',tail:'Kuyruk'};
document.querySelectorAll('[data-anim]').forEach(b=>b.onclick=()=>{anim=b.dataset.anim;document.querySelectorAll('[data-anim]').forEach(x=>x.classList.toggle('active',x===b));$('#animTitle').textContent=animNames[anim];animT=0;$('#time').value=0;draw()});
$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'❚❚':'▶';lastFrame=performance.now();if(playing)requestAnimationFrame(loop)};
$('#time').oninput=e=>{animT=+e.target.value/1000;$('#timeLabel').textContent=animT.toFixed(2)+'s';draw()};
$('#speed').oninput=e=>animSpeed=+e.target.value/100;$('#amp').oninput=e=>{animAmp=+e.target.value/100;draw()};
function loop(now){if(!playing)return;let dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;animT=(animT+dt*animSpeed)%1;$('#time').value=Math.round(animT*1000);$('#timeLabel').textContent=animT.toFixed(2)+'s';draw();requestAnimationFrame(loop)}
$('#bakePose').onclick=()=>{parts=parts.map(p=>displayPart(p));work='model';playing=false;$('#play').textContent='▶';document.querySelectorAll('[data-work]').forEach(x=>x.classList.toggle('active',x.dataset.work==='model'));$('#modelPanel').hidden=false;$('#animPanel').hidden=true;$('#modeBadge').textContent='MODEL';sync()};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{let v=b.dataset.view;if(v==='front'){yaw=0;pitch=0}else if(v==='side'){yaw=-Math.PI/2;pitch=0}else{yaw=0;pitch=-Math.PI/2+.02}draw()});$('#homeView').onclick=()=>{yaw=-.62;pitch=-.34;zoom=42;draw()};
C.onwheel=e=>{e.preventDefault();zoom=Math.max(12,Math.min(100,zoom*(e.deltaY>0?.9:1.1)));draw()};C.onpointerdown=e=>{C.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});drag={x:e.offsetX,y:e.offsetY};moved=false};C.onpointermove=e=>{if(!pointers.has(e.pointerId))return;let prev=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size===2){let a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch)zoom=Math.max(12,Math.min(100,zoom*d/pinch));pinch=d;moved=true;draw();return}if(drag){let dx=e.offsetX-drag.x,dy=e.offsetY-drag.y;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;yaw+=dx*.008;pitch=Math.max(-1.3,Math.min(1.3,pitch+dy*.008));drag={x:e.offsetX,y:e.offsetY};draw()}};C.onpointerup=e=>{pointers.delete(e.pointerId);pinch=0;if(!moved)pick(e.offsetX*(C.width/C.clientWidth),e.offsetY*(C.height/C.clientHeight));drag=null};$('#realCat').onclick=()=>{showReal=true;$('#realCat').classList.add('active');$('#ghost').textContent='Referans: Açık';draw()};$('#ghost').onclick=()=>{showReal=!showReal;$('#realCat').classList.toggle('active',showReal);$('#ghost').textContent='Referans: '+(showReal?'Açık':'Kapalı');draw()};window.onresize=draw;komodo();loadRealCat()})();